### ISSUE TITLE
errors while running tool

### ISSUE THREAD

**Issue by akashrpatil** [arbazkiraak/hackbot#13]
getting errors of libraries and not working with python2 and if I'm using with python3 throwing these errors.

```
root@kali:~/scripts/hackbot# python hackbot.py 
Traceback (most recent call last):
  File "hackbot.py", line 4, in <module>
    import telepot
ImportError: No module named telepot
root@kali:~/scripts/hackbot# python3 hackbot.py 
  File "hackbot.py", line 68
    print map(str,final)
          ^
SyntaxError: invalid syntax
root@kali:~/scripts/hackbot# 
```

**Comment by jcbm97** [comment]
That module was removed due to security concerns.

**Comment by kvvek** [comment]
How can we use this even am getting same error?
